//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvaluatieApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class Item
    {
        public int Id { get; set; }
        public string Title { get; set; }
        [AllowHtml]
        public string Description { get; set; }
        public string CreatedBy { get; set; }
        public string AuthorId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<double> Rating { get; set; }
        public Nullable<int> Type { get; set; }
    }
}
